-- Generated from generator/demo_specs/aws-philippines-bpo-client-portfolio.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-bpo-client-portfolio
-- This is the schema that is actually deployed for PH_BPO_CLIENT_PORTFOLIO.

-- Alerts fire on the bottom tail of Client Retention
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_CLIENT_RETENTION) AS T
  FROM RAW.DELIVERY_METRICS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_CLIENT_RETENTION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_CLIENT_RETENTION), 2) AS AVG_CLIENT_RETENTION,
  ROUND(AVG(f.KPI_CROSS_SELL_RATE), 2) AS AVG_CROSS_SELL_RATE,
  ROUND(AVG(f.KPI_AVG_CONTRACT_LENGTH), 2) AS AVG_CONTRACT_LENGTH
FROM RAW.DELIVERY_METRICS f
JOIN RAW.CLIENTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_CLIENT_RETENTION), 2) AS AVG_CLIENT_RETENTION,
  ROUND(AVG(f.KPI_CROSS_SELL_RATE), 2) AS AVG_CROSS_SELL_RATE,
  ROUND(AVG(f.KPI_AVG_CONTRACT_LENGTH), 2) AS AVG_CONTRACT_LENGTH
FROM RAW.DELIVERY_METRICS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_CLIENT_RETENTION) AS KPI_CLIENT_RETENTION, AVG(KPI_CROSS_SELL_RATE) AS KPI_CROSS_SELL_RATE, AVG(KPI_AVG_CONTRACT_LENGTH) AS KPI_AVG_CONTRACT_LENGTH FROM RAW.DELIVERY_METRICS),
     en AS (SELECT SUM(KPI_PORTFOLIO_REVENUE) AS KPI_PORTFOLIO_REVENUE, SUM(KPI_AT_RISK_ACCOUNTS) AS KPI_AT_RISK_ACCOUNTS, SUM(KPI_ACTIVE_CLIENTS) AS KPI_ACTIVE_CLIENTS, SUM(KPI_PIPELINE_VALUE) AS KPI_PIPELINE_VALUE FROM RAW.CLIENTS)
  SELECT 1 AS SORT_ORDER, 'Portfolio Revenue' AS TITLE, KPI_PORTFOLIO_REVENUE AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_PORTFOLIO_REVENUE) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Client Retention' AS TITLE, KPI_CLIENT_RETENTION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CLIENT_RETENTION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'At-Risk Accounts' AS TITLE, KPI_AT_RISK_ACCOUNTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AT_RISK_ACCOUNTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Clients' AS TITLE, KPI_ACTIVE_CLIENTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_CLIENTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Pipeline Value' AS TITLE, KPI_PIPELINE_VALUE AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_PIPELINE_VALUE) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Cross-Sell Rate' AS TITLE, KPI_CROSS_SELL_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CROSS_SELL_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Avg Contract Length' AS TITLE, KPI_AVG_CONTRACT_LENGTH AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_CONTRACT_LENGTH), 1) AS DECIMAL(38,1))) || ' ' || 'yrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
