-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Client Portfolio & Revenue Analytics
-- ============================================================================
USE DATABASE CLIENT_PORTFOLIO;
USE SCHEMA ML;

-- ML.CLASSIFICATION: CHURN_RISK_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.CHURN_RISK_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CLIENT_HEALTH_SCORE'),
  TARGET_COLNAME => 'CHURN_RISK_CATEGORY'
);

-- ML.FORECAST: REVENUE_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.REVENUE_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.REVENUE_360'),
  SERIES_COLNAME => 'CLIENT_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'MONTHLY_REVENUE'
  
);

CREATE OR REPLACE TABLE ML.REVENUE_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.REVENUE_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

