-- ============================================================================
-- 99_RESET.SQL — Reset Client Portfolio & Revenue Analytics to clean demo state
-- ============================================================================
USE DATABASE CLIENT_PORTFOLIO;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_HEALTH_SCORES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_EXPORT_ICEBERG SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_SUMMARIES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CLIENT_HEALTH_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.REVENUE_360 REFRESH;
ALTER DYNAMIC TABLE CURATED.RENEWAL_PIPELINE REFRESH;
ALTER DYNAMIC TABLE CURATED.PORTFOLIO_CONCENTRATION REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM CLIENT_PORTFOLIO.RAW.REVENUE_TRANSACTIONS → 340000
-- SELECT COUNT(*) FROM CLIENT_PORTFOLIO.RAW.DELIVERY_METRICS → 580000
-- SELECT COUNT(DISTINCT CLIENT_ID) FROM CLIENT_PORTFOLIO.CURATED.CLIENT_HEALTH_SCORE WHERE HEALTH_SCORE < 60 → 7

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_SUMMARIES RESUME;
ALTER TASK IF EXISTS APP.TASK_EXPORT_ICEBERG RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_HEALTH_SCORES RESUME;
